name: Close [skip ci] Update dependency PRs

# Schedule the workflow to run every 5 minutes
on:
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  close-skip-ci-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Close [skip ci] Update dependency PRs
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const pulls = await github.pulls.list({
              owner,
              repo,
              state: 'open'
            });

            for (const pull of pulls.data) {
              if (pull.title.startsWith('[skip ci] Update dependency')) {
                await github.pulls.update({
                  owner,
                  repo,
                  pull_number: pull.number,
                  state: 'closed'
                });
                console.log(`Closed PR #${pull.number} with title "${pull.title}"`);
              }
            }
