name: Close [skip ci] Update dependency PRs

on:
  schedule:
    - cron: '*/2 * * * *' # Every 5 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  close-skip-ci-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Close [skip ci] Update dependency PRs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const pulls = await github.rest.pulls.list({
              owner,
              repo,
              state: 'open'
            });

            const oneYearAgo = new Date();
            oneYearAgo.setFullYear(oneYearAgo.getFullYear() - 1);

            for (const pull of pulls.data) {
              const createdAt = new Date(pull.created_at);
              if (pull.title.startsWith('[skip ci] Update dependency') && createdAt < oneYearAgo) {
                await github.rest.pulls.update({
                  owner,
                  repo,
                  pull_number: pull.number,
                  state: 'closed'
                });
                console.log(`Closed PR #${pull.number} with title "${pull.title}" created at "${pull.created_at}"`);
              }
            }
